In [1]:
import pandas as pd
import nltk 
nltk.download('words')
WORDS = set(nltk.corpus.words.words())
WORDS = [w.lower() for w in WORDS]

[nltk_data] Downloading package words to /home/manpreet/nltk_data...
[nltk_data]   Package words is already up-to-date!

### Function to remove Non - English words using nltk

In [2]:
def remove_non_english_words(text,words=WORDS):
    '''
    converts a text into lower case and checks if the words are in english,
    else removes them.
    '''
    text = str(text).lower()
    return " ".join([w for w in text.split() if w in words])


remove_non_english_words('roTi iS nOt an EnGliSh woRd')

'is not an english word'

### Read the raw data and drop duplicate entries

In [3]:
raw_df = pd.read_excel('../data/raw_data.xlsx')
raw_df = raw_df[['Department','Rating']]
raw_df.columns = ['Department','Complaint']
df = raw_df.drop_duplicates()
df.head()

         Department                                          Complaint
0      Encroachment  Topkapi in seasons mall is playing music on lo...
1          Drainage                        Dranage over flow freqently
2        Electrical                        Street light is not working
3  Traffic-Planning  Please repair road at kpndwa flyover kondhwa pune
4        Electrical  Please make street light functional at Divya n...

### Using Groupby to get a rough idea about the raw data

In [4]:
grouped_df = df.groupby('Department').count()
grouped_df.sort_values('Complaint',ascending=False)

                            Complaint
Department
Garbage (SWM)                    4402
Electrical                       3902
Road Project(H.O)                3144
Water Supply                     3093
Building Permission              2851
Road                             2752
Drainage                         2208
Garden                           1823
Property Tax                     1546
Encroachment                     1534
Stray Dogs                       1472
Health                           1430
Health Kitak                     1297
Traffic-Planning                  774
License-Skysign                   461
Drainage Project(H.O)             269
Bhavan Rachana Department         256
Traffic-signal(Electrical)        224
Health (H.O)                      176
Slum                              138
Estate and Management (HO)        122
Information Technology            115
Noise Pollution                   112
Garden - Civil                     81
SWM (HO)                           67
Birth And Death                    66
Bhavan (H.O)                       59
Garden - Electrical                34
Social Development                 29
Encroachment (HO)                   9
Mandai                              9
License_Skysign (HO)                8
Sports                              8
Education                           5
Legal                               5
Pune Smart City (PSCDCL)            4
Developement Planning               4
City Engineer                       4
Other                               1
Solar Project                       1

In [5]:
df = df.set_index('Department')
df.to_excel('../data/temp.xlsx')

In [7]:
cleaned_df = pd.DataFrame()

for _,row in df.iterrows():
    label = row.name
    text = remove_non_english_words(row.Complaint)
    
    if len(text) and label:
        cleaned_df = cleaned_df.append([[text,label]])
    
    if cleaned_df.shape[0] % 1000 == 0:
        print(cleaned_df.shape[0])

1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000

In [8]:
cleaned_df.columns = ['text', 'label']
cleaned_df = cleaned_df.set_index('label')
cleaned_df.to_excel('../data/cleaned_df.xlsx')

In [9]:
grouped_df = cleaned_df.groupby(cleaned_df.index).count()
grouped_df.sort_values('text',ascending=False)

                            text
label
Garbage (SWM)               3952
Electrical                  3544
Road Project(H.O)           2924
Water Supply                2864
Road                        2425
Building Permission         2053
Drainage                    1923
Garden                      1595
Property Tax                1488
Encroachment                1369
Stray Dogs                  1344
Health                      1248
Health Kitak                1127
Traffic-Planning             722
License-Skysign              373
Drainage Project(H.O)        242
Traffic-signal(Electrical)   209
Bhavan Rachana Department    157
Health (H.O)                 141
Noise Pollution              111
Information Technology       111
Estate and Management (HO)    93
Slum                          89
Garden - Civil                68
Birth And Death               62
SWM (HO)                      56
Bhavan (H.O)                  45
Garden - Electrical           31
Social Development            27
Encroachment (HO)              8
License_Skysign (HO)           7
Mandai                         6
Sports                         5
City Engineer                  4
Legal                          4
Pune Smart City (PSCDCL)       4
Developement Planning          3
Education                      2
Solar Project                  1
Other                          1